// .tmf container conformance — verified byte-for-byte against the frozen golden vector
// (LogicN-R-AND-D/tmf/spec/tmf-container-v0.md §8, generated by gen_tmf_container.py) + the §6
// fail-closed reader (round-trip + every error in the §7 taxonomy).
import { test } from "node:test";
import assert from "node:assert/strict";
import { writeTmf, readTmf, TmfError, headerCore, tmxRoot, leafHash } from "../dist/index.js";

const hex = (u) => Buffer.from(u).toString("hex");
const enc = new TextEncoder();
const le32 = (x) => { const b = new Uint8Array(4); new DataView(b.buffer).setUint32(0, x >>> 0, true); return b; };
const cat = (...ps) => { const t = ps.reduce((n, p) => n + p.length, 0); const o = new Uint8Array(t); let k = 0; for (const p of ps) { o.set(p, k); k += p.length; } return o; };
const coord = (x, y, t) => cat(le32(x), le32(y), le32(t));
const isCode = (code) => (e) => e instanceof TmfError && e.code === code;

const golden = [
  { kind: 1, modality: 0, coord: coord(3, 5, 7), payload: enc.encode("hello") },
  { kind: 1, modality: 2, coord: coord(3, 5, 8), payload: enc.encode("world!") },
];

const GOLDEN_HEX =
  "89544d460d0a1a0a0000000000000000" +
  "020000000000000043386e644c7b53aa" +
  "0900cda21c15acd15f30b3fdf997950e" +
  "39e7dd3dbc685212010000000c000000" +
  "00000000000000001100000000000000" +
  "34eb47169cfaf5b3fac19670624c4dc4" +
  "d7002838be5542625d6a90d2a5eefc72" +
  "010002000c0000001100000000000000" +
  "120000000000000065a4d5568838d568" +
  "e1bfe45f96997b251674425a6243dc04" +
  "da1ca548d211594b0300000005000000" +
  "0700000068656c6c6f03000000050000" +
  "0008000000776f726c6421";

test("writeTmf reproduces the golden container byte-for-byte (203 bytes)", () => {
  const out = writeTmf(golden);
  assert.equal(out.length, 203);
  assert.equal(hex(out), GOLDEN_HEX);
});

test("integrity_root (header bytes 24:56) equals the TMX golden root", () => {
  assert.equal(hex(writeTmf(golden).subarray(24, 56)), "43386e644c7b53aa0900cda21c15acd15f30b3fdf997950e39e7dd3dbc685212");
});

test("readTmf round-trips a written container (fail-closed reader accepts a clean file)", () => {
  const r = readTmf(writeTmf(golden));
  assert.equal(r.sections.length, 2);
  assert.equal(r.profile, 0);
  assert.equal(r.flags, 0);
  assert.equal(Buffer.from(r.sections[0].payload).toString(), "hello");
  assert.equal(Buffer.from(r.sections[1].payload).toString(), "world!");
  assert.equal(r.sections[1].modality, 2);
});

test("tamper (payload 'hello' → 'Hello') → IntegrityError", () => {
  const t = writeTmf(golden).slice();
  t[180] = 0x48; // payload0 starts at region_off(168)+coord_len(12) = 180
  assert.throws(() => readTmf(t), isCode("IntegrityError"));
});

test("trailing byte on an unsigned file → MalformedTable", () => {
  assert.throws(() => readTmf(cat(writeTmf(golden), Uint8Array.from([0x00]))), isCode("MalformedTable"));
});

test("truncated header → MalformedTable", () => {
  assert.throws(() => readTmf(writeTmf(golden).subarray(0, 40)), isCode("MalformedTable"));
});

test("bad magic → BadMagic", () => {
  const t = writeTmf(golden).slice();
  t[0] = 0x00;
  assert.throws(() => readTmf(t), isCode("BadMagic"));
});

test("unknown tmx_profile → UnknownProfile (checked before any hashing)", () => {
  const t = writeTmf(golden).slice();
  t[12] = 0x09; // tmx_profile = 9
  assert.throws(() => readTmf(t), isCode("UnknownProfile"));
});

test("coord_len > blob_len → MalformedTable", () => {
  const t = writeTmf(golden).slice();
  // entry0.coord_len at offset 56+4 = 60; set to 0xff (> blob_len 17)
  t[60] = 0xff;
  assert.throws(() => readTmf(t), isCode("MalformedTable"));
});

test("a signed file with a correct signed-root is rejected AuthError (no silent downgrade)", () => {
  const tableAndRegion = writeTmf(golden).subarray(56); // table + region are identical signed/unsigned
  const leaf0 = leafHash(1, 0, coord(3, 5, 7), enc.encode("hello"));
  const leaf1 = leafHash(1, 2, coord(3, 5, 8), enc.encode("world!"));
  const hcSigned = headerCore(0, 1, 2); // flags.signed = 1
  const rootSigned = tmxRoot(hcSigned, [leaf0, leaf1]);
  const signedFile = cat(hcSigned, rootSigned, tableAndRegion, Uint8Array.from([0x01, 0x00])); // dummy sig block (trailing allowed when signed)
  assert.throws(() => readTmf(signedFile), isCode("AuthError"));
});
